# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.5
language: swift
cache: cocoapods
podfile: Podfile

before_install:
- bundle install
- pod install

script:
- pod lib lint
- xcodebuild clean build test -workspace "SwanKit.xcworkspace" -scheme "SwanKit_iOS" -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
- bash <(curl -s https://codecov.io/bash)
- pod trunk push
